version = 0.1

[default.global.parameters]
stack_name = "intrack-expense-tracker"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
  "GitLabProjectId=REPLACE_WITH_PROJECT_ID",
  "GitLabTokenSecretArn=arn:aws:secretsmanager:REGION:ACCOUNT:secret:gitlab-token-XXXXXX",
  "AuthSecretArn=arn:aws:secretsmanager:REGION:ACCOUNT:secret:intrack-auth-XXXXXX"
]

[default.package.parameters]
resolve_s3 = true
